/*
 * This source file was generated by the Gradle 'init' task
 */
package com.romanhan;

import java.util.Scanner;

import com.romanhan.game.Game;

public class WarGame {

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        Game game = new Game(scanner);
        game.game();
    }
}
