/*
 * This source file was generated by the Gradle 'init' task
 */
package com.romanhan;

import com.romanhan.cards.Rank;
import com.romanhan.cards.Suit;

public class WarGame {

    public static void main(String[] args) {
        System.out.println("War game");
        Rank ace = Rank.ACE;
        Suit clubs = Suit.CLUBS;

        System.out.printf("[%s%c]", ace.getName(), clubs.getValue());
    }
}
