/*
 * This source file was generated by the Gradle 'init' task
 */
package com.romanhan;

import java.util.Scanner;

public class WarGame {

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        new Game(scanner);
        System.out.println("War game started");
    }
}
