/*
 * This source file was generated by the Gradle 'init' task
 */
package com.romanhan;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class WarGameTest {
    @Test void appHasAGreeting() {
        WarGame classUnderTest = new WarGame();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
